version: '3.9'

services:
  api:
    image: node:20-bullseye
    container_name: nx-arag-api
    working_dir: /workspace
    command: >-
      sh -c "corepack enable &&
      yarn install --frozen-lockfile &&
      yarn dev:api"
    env_file:
      - ../../apps/api/.env.example
    environment:
      NODE_ENV: development
      PORT: ${PORT:-3000}
      DD_ENV: ${DD_ENV:-development}
      DD_SERVICE: ${DD_SERVICE:-nx-arag-api}
      DD_VERSION: ${DD_VERSION:-local}
      DD_TRACE_AGENT_URL: http://datadog-agent:8126
      DD_AGENT_HOST: datadog-agent
      DD_TRACE_ENABLED: ${DD_TRACE_ENABLED:-true}
      DD_LOGS_INJECTION: ${DD_LOGS_INJECTION:-true}
      DD_RUNTIME_METRICS_ENABLED: ${DD_RUNTIME_METRICS_ENABLED:-false}
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - ../..:/workspace
      - api-node-modules:/workspace/node_modules
    labels:
      com.datadoghq.logs: '[{"service":"nx-arag-api","source":"nodejs","env":"${DD_ENV:-development}"}]'
      com.datadoghq.tags.env: ${DD_ENV:-development}
      com.datadoghq.tags.service: nx-arag-api
      com.datadoghq.tags.version: ${DD_VERSION:-local}
    depends_on:
      - datadog-agent

volumes:
  api-node-modules:
